.TH "ILLUMINATE" "1" "April 6, 2019" "illuminate"
.SH "NAME"
illuminate \- system information viewer for illumos
.SH "SYNOPSIS"
.LP
illuminate subcommand [arguments]
.SH DESCRIPTION
.LP
The illuminate utility allows the user to see a graphical display of some
properties of a computer running an illumos distribution.
.LP
Specifically, it allows you to browse SMF services, display the output
of useful informational commands, explore the properties of your
system, and investigate installed software packages on Tribblix.
.LP
To see the available subcommands, run illuminate help.
.SH SEE ALSO
.LP
jkstat(1), jproc(1)
.SH NOTES
.LP
Only SVR4 packages are currently understood. As a result, the software
view is only useful on an illumos distribution like Tribblix that uses
SVR4 packaging.
