./" SPDX-FileCopyrightText: 2025 Peter Tribble
./" SPDX-License-Identifier: CDDL-1.0
.TH "ILLUMINATE" "1" "May 26, 2020" "illuminate"
.SH "NAME"
illuminate \- system information viewer for illumos
.SH "SYNOPSIS"
illuminate subcommand [arguments]
.SH DESCRIPTION
The illuminate utility allows the user to see a graphical display of some
properties of a computer running an illumos distribution.
.LP
Specifically, it allows you to browse SMF services, display the output
of useful informational commands, explore the properties of your
system, and investigate installed software packages on Tribblix.
.LP
To see the available subcommands, run illuminate help.
.SH SEE ALSO
jkstat(1), jproc(1)
.SH NOTES
Only SVR4 packages are currently understood. As a result, the software
view is only useful on an illumos distribution like Tribblix that uses
SVR4 packaging.
